package com.bank.islamic.ifsbregulatoryreporting;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: IFSB Regulatory Reporting
 *
 * Business Area:      Takaful and Shared Operations
 * Business Domain:    Shared Operations
 * Functional Pattern: Process
 * Asset Type:         IFSB Regulatory Report
 * Control Record:     IFSB Regulatory Report Procedure
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("IFSB Regulatory Reporting — BIAN Semantic API")
                .description("Service Domain 'IFSB Regulatory Reporting' (Process pattern) "
                        + "operating on the 'IFSB Regulatory Report Procedure' control record.")
                .version("0.1.0"));
    }
}
